site_name: Spyduster Documentation
site_description: Documentation for the Spydus library system client
repo_url: https://github.com/multimeric/spyduster

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - content.code.copy

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            show_source: false
            show_bases: false
            heading_level: 3
            show_root_heading: true
            separate_signature: false
            show_signature_annotations: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - api.md